### ISSUE TITLE
Reconocimiento GPS

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-team-lmn#1]
[Practica 8.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-team-lmn/files/15278596/Practica.8.pdf)

**Comment by josealfredo79** [comment]
Se necesita la calificacion...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
